logging:
  level:
    ROOT: info

server:
  port: 8000
  servlet:
    context-path: /mogi
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATASOURCE_URL}
    username: mfrmahfqwipajx
    password: 34e5b925bc8c6c4536ba9fcd4b1a43cc9710c35c796f47ef856eb0f7c3fb93a7
  jpa:
    generate-ddl: true

    